---
title: "Purple Air Sensors"
author: "Mazama Science"
date: "2019-06-13"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Purple Air Sensors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=5)
library(AirSensor)
```

This vignette decribes technical details of Purple Air Sensor internals.

## General Description

The PurpleAir PA-II sensor tracks real-time atmospheric measurements including 
particulate matter (PM) concentrations, temperature, humidity, and pressure. The
device is connected via wifi to the ThingSpeak "internet of things" platform 
where readings are stored and can be retrieved.

1. [PurpleAir technology overview](https://www2.purpleair.com/pages/technology)
2. [AQ-SPEC evaluation](https://www.aqmd.gov/aq-spec/product/purpleair-pa-ii)

## Internal Hardware

### Particle Detectors

PM levels are measured using two
[Plantower PMS5003 Particle Detectors](http://www.aqmd.gov/docs/default-source/aq-spec/resources-page/plantower-pms5003-manual_v2-3.pdf)
which provide their own separate 'A' and 'B' reading channels. Optical particle 
counters of this type function by measuring light scattered by particulate 
matter. The PMS5003 unit sends a laser through air sucked in by a fan, measures 
the light received, and calculates the number of different-sized particles based
on [Mie scattering](https://en.wikipedia.org/wiki/Mie_scattering) algorithms.

The detectors' effective range for PM2.5 lies between 0 and 500 ug/m3, but can 
still measure beyond 1000 ug/m3. The operational temperature ranges
from -10 to 60 C, and humidity anywhere between 0-99 RH%.

[More on optical particle counting](http://www.cas.manchester.ac.uk/restools/instruments/aerosol/opc/) 

### Temperature/Humidity/Pressure Sensor

Temperature, relative humidity, and pressure are all measured by a single 
[Bosch Sensortec Intergrated Environmental Sensor Unit BME280](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME280-DS002.pdf).
The manufacturer has provided both 'operational' and 'full-accuracy' ranges for
the individual sensors:

* Temperature sensor
  + Operational: -40 to 85 C.
  + Full-accuracy: 0 to 65 C.
* Humidity sensor
  + Operational: -40 to 85 C. 0 to 100 %RH.
* Pressure sensor
  + Operational: -40 to 85 C. 0 to 100 %RH.
  + Full-accuracy range: 0 to 65 C. 300 to 1100 hPa.

## Internal Firmware

### Sampling Protocol

The firmware in each PA sensor is in charge of communicating with the internal
particle detectors and averaging instantaneous measurements over a sampling
period before reporting the sampling-period averaged value back over wifi.

From internal communication with PurpleAir:

```
Do the reported pm2.5 values in the raw data represent instantaneous values or 
does the PA sensor firmware do some averaging? If the firmware does averaging, 
what is the underlying sampling period -- i.e. how many particle counter
measurements does the firmware average together before reporting every 80/120 
seconds?

----- >8 -----

The PM data is averaged over a sampling period. For PA-II and PA-II-SD sensors
that contain 2 laser counters (Channel A and Channel B) they alternate averaging
5 1-second measurements over the sampling period, which is 80 seconds for
firmware versions 3.00 and orders and 120 seconds for firmware versions 4.00 and
later. So Channel A will measure to 5 seconds and then Channel B will measure
for 5 seconds, then back to Channel A, etc. At the end of the sampling period
Channel A will be a cumulative 40s/60s average over the sampling period of
80s/120s and Channel B will be a cumulative 40s/60s average of the other half of
that 80s/120s sampling period.

----- >8 -----

Just to make sure I've got it:

If each letter is 1 sec then we have, for an 80 second sampling period:

AAAAA-----AAAAA-----AAAAA-----AAAAA-----AAAAA-----AAAAA-----AAAAA-----AAAAA-----
-----BBBBB-----BBBBB-----BBBBB-----BBBBB-----BBBBB-----BBBBB-----BBBBB-----BBBBB

So the pm2.5 value reported for the A channel at the end of 80 seconds actually
consists of 40 separate measurements, spaced as shown. And similarly for the B
channel.

Is that correct?

----- >8 -----

That is correct!
```

