FROM mazamascience/mazamapurpleair:0.1.6
MAINTAINER "Jonathan Callahan" jonathan@mazamascience.com

################################################################################
# Install packages required for operational scripting
RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    optparse

## Install latest development versions of packages
#RUN installGithub.r \
#    MazamaScience/MazamaPurpleAir


