################################################################################
# Makefile for building and running docker containers
#
# PRODUCTION version
production_build:
	docker build --no-cache -t sensor-data-ingest-v1:0.1.6 -t sensor-data-ingest-v1:latest -f Dockerfile .

