################################################################################
# Makefile for installing scripts on a server
#

createArchiveDirs:
	mkdir -p /var/www/html/data/PurpleAir/airsensor/2018
	mkdir -p /var/www/html/data/PurpleAir/airsensor/2019
	mkdir -p /var/www/html/data/PurpleAir/airsensor/latest
	mkdir -p /var/www/html/data/PurpleAir/logs
	mkdir -p /var/www/html/data/PurpleAir/pas/2018
	mkdir -p /var/www/html/data/PurpleAir/pas/2019
	mkdir -p /var/www/html/data/PurpleAir/pat/2018
	mkdir -p /var/www/html/data/PurpleAir/pat/2019
	mkdir -p /var/www/html/data/PurpleAir/pat/latest
	mkdir -p /var/www/html/data/PurpleAir/videos/2018
	mkdir -p /var/www/html/data/PurpleAir/videos/2019

